version: '3'
services:
  api:
    image: sample
    build: .
    restart: always
    ports:
      - "3000:3000"    
    depends_on:
      - "mongo"  
  mongo:
    image: "mongo"
    restart: always
    ports: 
      - "27018:27017"
    command: mongod --port 27018  
    volumes: 
      - ./data:/data/db    