version: '3'
services:
  api:
    image: sample-express-app
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes: 
      - ./app_test:/usr/src/app    
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    restart: always
    ports: 
      - "27018:27017"
    command: mongod --port 27018  
    volumes: 
      - ./data:/data/db    