version: '3'
services:
  api:
    image: sample-express-app
    build: .
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    restart: always
    ports: 
      - "27018:27017"
    volumes: 
      - ./data:/data/db    